apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: swr.ap-southeast-3.myhuaweicloud.com/test-fq/jenkins-demo:latest
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
