name: CI Workflow

on: [push]

jobs:
  package:
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v4
    - name: Package step
      run: |
        echo "hello"
        echo "package"

  build:
    needs: package
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0
    - name: Login to Docker
      run: echo "${{ secrets.SWR_SK }}" | docker login -u ${{ secrets.PROJECT }}@${{ secrets.SWR_AK }} swr.ap-southeast-3.myhuaweicloud.com --password-stdin
    - name: Build and push Docker image
      run: |
        docker build -t swr.${{ secrets.PROJECT }}.myhuaweicloud.com/${{ secrets.ORGANIZATION }}/jenkins-demo:${{ github.run_id }} .
        docker push swr.${{ secrets.PROJECT }}.myhuaweicloud.com/${{ secrets.ORGANIZATION }}/jenkins-demo:${{ github.run_id }}

