name: CI Workflow

on: [push]

jobs:
  package:
    runs-on: arc-runner-set
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v2
    - name: Package step
      run: |
        echo "hello"
        echo "package"
