name: CI Workflow

on: [push]

jobs:
  package:
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v4
    - name: Package step
      run: |
        echo "hello"
        echo "package"
  build:
    needs: package
    runs-on: arc-runner-set
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: swr.${{ secrets.PROJECT }}.myhuaweicloud.com
        username: ${{ secrets.PROJECT }}@${{ secrets.SWR_AK }}
        password: ${{ secrets.SWR_SK }}
    - name: List All File
      run: "ls -la"
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: "swr.${{ secrets.PROJECT }}.myhuaweicloud.com/${{ secrets.ORGANIZATION }}/jenkins-demo:${{ github.run_id }}"
    - name: Inspect
      run: |
        docker image inspect swr.${{ secrets.PROJECT }}.myhuaweicloud.com/${{ secrets.ORGANIZATION }}/jenkins-demo:${{ github.run_id }}
