name: CI Workflow

on: [push]

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: get CCE Cluster Credentials
        uses: huaweicloud/cce-credential-action@v1.0.0
        with:
          ak: ${{ secrets.SWR_AK }}
          sk: ${{ secrets.PROJECT_SK }}
          region: ${{ secrets.PROJECT }}
          project_id: ${{ secrets.PROJECT_ID }}
          cluster_id: ${{ secrets.CLUSTER_ID }}
      - name: get CCE Cluster info
        run: |
          kubectl cluster-info
